name: MacSync
options:
  bundleIdPrefix: com.macsync
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  MacSync:
    type: application
    platform: macOS
    sources:
      - path: MacSync
        excludes:
          - "Resources/MacSync.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macsync.app
        PRODUCT_NAME: MacSync
        INFOPLIST_GENERATION_MODE: GeneratedByXcode
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
        CODE_SIGN_ENTITLEMENTS: MacSync/Resources/MacSync.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: "NO"
        SWIFT_EMIT_LOC_STRINGS: "YES"
    entitlements:
      path: MacSync/Resources/MacSync.entitlements
  MacSyncTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MacSyncTests
    dependencies:
      - target: MacSync
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macsync.app.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MacSync.app/Contents/MacOS/MacSync"
        BUNDLE_LOADER: "$(TEST_HOST)"
